name: bloc_architecture
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

    #UI
  cupertino_icons: ^1.0.2

  #State Management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  #Network
  dio: ^5.1.1

  #Utils
  kartal: ^2.8.0
  dartz: ^0.10.1
  sizer: ^2.0.15

  #Dependency Injection
  get_it: ^7.3.0

  #Storage
  flutter_secure_storage: ^8.0.0

  #Language
  easy_localization: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pretty_dio_logger: ^1.3.1
flutter:
  uses-material-design: true


